---
title: "Prática em Análise de Conteúdo Quantitativa"
author: "Cláudio A. Monteiro"
date: "27 de novembro de 2017"
output: html_document
---

<style>
body {
text-align: justify}
</style>


# INTRODUÇÃO

Como categorizar e analisar documentos de forma automática? Este projeto busca responder esta resposta de forma intuitiva a partir da interação da técnica de *Análise de Conteúdo* com a *Mineração de Texto*, levantando seus principais conceitos e a demonstrando na prática. Para tal será exposto dois exemplos de análises de documentos envolvendo (1) Análise de reuniões de arenas democráticas (conselhos gestores) e (2) análise de documentos políticos e partidários (manifesto partidário e programa de governo). Toda a análise será feita em linguagem de programação R.

## Preguiça: O motor da programação

**Por que aprender linguagem de programação?** A resposta é simples: fazer mais em menos tempo.

Trabalhar com documentos envolve uma série de problemas, o formato do arquivo pode adicionar mais trabalho pra fazer qualquer tipo de manipulação com o documento (.pdf é a tristeza, se tiver em imagem então...), os arquivos podem vir corrompidos, ou simplesmente você pode ter uma quantitade absurda de documentos (lembro de um projeto que o objetivo era extrair informações de cerca de 17.000 processos judiciários do Conselho Nacional de Justiça - CNJ).

Mas nem tudo está perdido! Linguagens de programação são desenvolvidas justamente para executar tarefas e solucionar problemas.








